### ISSUE TITLE
Using the new Quicklinks to quickly and simple jump to special areas in wwSchool.

### ISSUE THREAD

**Issue by Cameo007** [J0J0HA/wwshc#3]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Nothing

**Describe alternatives you've considered**
No

**Additional context**
![Screenshot_20230425_220059_WebWeaver.jpg](https://user-images.githubusercontent.com/80521473/234389664-2a1b4440-fa77-4c07-81a9-d8c4ddad8e45.jpg)

__

**Comment by J0J0HA** [comment]
Was this meant as a suggestion to make it faster?

I would discontinue and archive this project now, so this will not be implemented.
Maybe I will start this over again in the future, but that is not my plan at the moment.

I just can't change the current code, it is too messy.
